= k3 Case study in BASAALT/Form-L
:favicon: images/cocovad-logo.png
:version: 2023.08.1
// icons for GitHub
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
//-------------------------------------

:cocovad: https://github.com/CoCoVaD/website[CoCoVaD chair]
:cfp: https://www.sosym.org/theme_sections/cfp/cfp-SoSyM-TS-Requirements-Formalisation-2023.pdf

//------------------------------------ Badges --------
:baseURL: https://github.com/CoCoVaD/k3c
//image:{baseURL}/actions/workflows/main.yml/badge.svg[Deployed] 
image:https://img.shields.io/github/license/:jmbruel/:https://github.com/CoCoVaD/k3c[GitHub]
//------------------------------------ Badges --------

This repo is dedicated to the `k3` case study requirements using the <<basaalt,BASAALT>> systems engineering method.
It collects the available material for repeatability and reproducibility.

== Context

This case study is part of a link:{cfp}[SoSyM Theme Section] on "Requirements Formalisation: From Text to Model-based."

== Available Material

NOTE: This material is available in the `doc` folder of this repo.

- The initial text (link:doc/k3_initial_requirements.docx[.docx])
- The Data Model in Form-L (link:doc/k3DataModel.pdf[.pdf])
- The Requirements in Form-L (link:doc/k3Requirements.pdf[.pdf])

[[basalt]]
== The BASAALT Approach

The BASAALT (Behaviour Analysis & Simulation All Along systems Life Time) systems engineering method, 
and its supporting language, FORM-L (FOrmal Requirements Modelling Language) are advocated in our submission to the link:{cfp}[SoSyM Theme Section] on "Requirements Formalisation: From Text to Model-based." 

NOTE: The full documentation is available in a PDF report link:doc/BASAALT-and-FORM-L.pdf[here].
